---
- name: Clean up VM Subnet with WireGuard VPN Routing
  hosts: proxmox_hosts
  become: true
  vars:
    vm_subnet: "10.10.0.0/24"
    routing_table_id: 200

  tasks:
    - name: Disarm network failsafe if active
      ansible.builtin.command: /usr/local/bin/disarm-failsafe.sh
      register: failsafe_disarm_result
      failed_when: false
      changed_when: failsafe_disarm_result.rc == 0

    - name: Stop WireGuard service
      ansible.builtin.systemd:
        name: wg-quick@wg0
        state: stopped
        enabled: false
      failed_when: false

    - name: Stop dnsmasq service
      ansible.builtin.systemd:
        name: dnsmasq@vmwgnat
        state: stopped
        enabled: false
      failed_when: false

    - name: Re-enable default dnsmasq service (optional - was disabled for Proxmox)
      ansible.builtin.systemd:
        name: dnsmasq
        state: stopped
        enabled: false
      failed_when: false
      # Note: We keep it disabled as per Proxmox best practices
      # Change 'enabled: false' to 'enabled: true' if you want to restore it

    - name: Check if vmwg0 interface exists
      ansible.builtin.command: ip link show vmwg0
      register: vmwg0_check
      failed_when: false
      changed_when: false

    - name: Bring down vmwg0 interface
      ansible.builtin.command: ifdown vmwg0
      when: vmwg0_check.rc == 0
      register: ifdown_result
      failed_when: false
      changed_when: ifdown_result.rc == 0

    - name: Check existing NAT rules
      ansible.builtin.command: iptables -t nat -C POSTROUTING -s "{{ vm_subnet }}" -o wg0 -j MASQUERADE
      register: nat_rule_check
      failed_when: false
      changed_when: false

    - name: Clean up NAT rules
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        source: "{{ vm_subnet }}"
        out_interface: wg0
        jump: MASQUERADE
        state: absent
      when: nat_rule_check.rc == 0

    - name: Check existing CT rules
      ansible.builtin.command: iptables -t raw -C PREROUTING -i fwbr+ -j CT --zone 1
      register: ct_rule_check
      failed_when: false
      changed_when: false

    - name: Clean up CT rules using command (iptables module doesn't support --zone)
      ansible.builtin.command: iptables -t raw -D PREROUTING -i fwbr+ -j CT --zone 1
      when: ct_rule_check.rc == 0
      register: ct_cleanup_result
      failed_when: false
      changed_when: ct_cleanup_result.rc == 0

    - name: Check and clean up FORWARD rules (vmwg0 -> wg0)
      ansible.builtin.command: iptables -C FORWARD -i vmwg0 -o wg0 -j ACCEPT
      register: forward_rule_check1
      failed_when: false
      changed_when: false

    - name: Remove FORWARD rule (vmwg0 -> wg0)
      ansible.builtin.iptables:
        chain: FORWARD
        in_interface: vmwg0
        out_interface: wg0
        jump: ACCEPT
        state: absent
      when: forward_rule_check1.rc == 0

    - name: Check and clean up FORWARD rules (wg0 -> vmwg0)
      ansible.builtin.command: iptables -C FORWARD -i wg0 -o vmwg0 -m state --state RELATED,ESTABLISHED -j ACCEPT
      register: forward_rule_check2
      failed_when: false
      changed_when: false

    - name: Remove FORWARD rule (wg0 -> vmwg0)
      ansible.builtin.iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: vmwg0
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT
        state: absent
      when: forward_rule_check2.rc == 0

    - name: Check existing policy routing rules
      ansible.builtin.shell: |
        set -o pipefail
        ip rule show | grep -q "from {{ vm_subnet }} lookup {{ routing_table_id }}" ||
        ip rule show | grep -q "to {{ vm_subnet }} lookup {{ routing_table_id }}"
      args:
        executable: /bin/bash
      register: policy_rules_check
      failed_when: false
      changed_when: false

    - name: Clean up policy routing rules
      ansible.builtin.shell: |
        set -o pipefail
        changed=false
        if ip rule show | grep -q "from {{ vm_subnet }} lookup {{ routing_table_id }}"; then
          ip rule del from {{ vm_subnet }} table {{ routing_table_id }}
          changed=true
        fi
        if ip rule show | grep -q "to {{ vm_subnet }} lookup {{ routing_table_id }}"; then
          ip rule del to {{ vm_subnet }} table {{ routing_table_id }}
          changed=true
        fi
        if [ "$changed" = "true" ]; then
          echo "Rules removed"
        fi
      args:
        executable: /bin/bash
      register: policy_cleanup_result
      when: policy_rules_check.rc == 0
      changed_when: "'Rules removed' in policy_cleanup_result.stdout"

    - name: Check if routing table has entries
      ansible.builtin.command: ip route show table {{ routing_table_id }}
      register: routing_table_check
      failed_when: false
      changed_when: false

    - name: Clean up routing table
      ansible.builtin.shell: |
        if [ -n "$(ip route show table {{ routing_table_id }})" ]; then
          ip route flush table {{ routing_table_id }}
          echo "Table flushed"
        fi
      register: route_cleanup_result
      when: routing_table_check.stdout != ""
      changed_when: "'Table flushed' in route_cleanup_result.stdout"

    - name: Remove configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/wireguard/wg0.conf
        - /etc/network/interfaces.d/vmwgnat
        - /etc/dnsmasq.d/vmwgnat
        - /etc/systemd/system/dnsmasq@.service
        - /etc/systemd/system/wg-quick@wg0.service.d
        - /root/debug-vmwg0.sh
        - /root/fix-vm-connectivity.sh
        - /usr/local/bin/network-failsafe.sh
        - /usr/local/bin/disarm-failsafe.sh
        - /var/backups/network-failsafe
        - /tmp/network-failsafe.lock

    - name: Remove vmwg0 bridge from main Proxmox interfaces file
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE MANAGED BLOCK - vmwg0"
        state: absent
        backup: true

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Check if iptables rules need saving
      ansible.builtin.stat:
        path: /etc/iptables/rules.v4
      register: iptables_file
      when: ansible_facts['os_family'] == "Debian"

    - name: Save clean iptables rules
      ansible.builtin.shell: |
        iptables-save > /etc/iptables/rules.v4
        ip6tables-save > /etc/iptables/rules.v6
        echo "Rules saved"
      register: iptables_save_result
      when:
        - ansible_facts['os_family'] == "Debian"
        - iptables_file.stat.exists
      changed_when: "'Rules saved' in iptables_save_result.stdout"

    - name: Restart networking
      ansible.builtin.systemd:
        name: networking
        state: restarted
