---
- name: Deploy VM WireGuard Network Configuration
  hosts: proxmox_hosts
  become: true
  vars:
    vm_subnet: "10.10.0.0/24"
    vm_gateway: "10.10.0.1"
    vm_dhcp_range_start: "10.10.0.2"
    vm_dhcp_range_end: "10.10.0.254"
    wireguard_interface: "wg0"
    vm_bridge_interface: "vmwg0"
    dhcp_lease_time: "12h"
    mtu_size: 1380

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - wireguard-tools
          - dnsmasq
          - iptables-persistent
          - resolvconf
        state: present
        update_cache: true

    - name: Create WireGuard configuration directory
      ansible.builtin.file:
        path: /etc/wireguard
        state: directory
        mode: "0700"
        owner: root
        group: root

    - name: Deploy WireGuard configuration
      ansible.builtin.template:
        src: templates/wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
        owner: root
        group: root
      notify:
        - Restart wireguard

    - name: Create dnsmasq configuration directory for vmwgnat
      ansible.builtin.file:
        path: /etc/dnsmasq.d/vmwgnat
        state: directory
        mode: "0755"

    - name: Deploy dnsmasq default configuration
      ansible.builtin.copy:
        src: src/dnsmasq.d/vmwgnat/00-default.conf
        dest: /etc/dnsmasq.d/vmwgnat/00-default.conf
        mode: "0644"
      notify:
        - Restart dnsmasq

    - name: Deploy dnsmasq vmwg0 interface configuration
      ansible.builtin.template:
        src: templates/10-vmwg0.conf.j2
        dest: /etc/dnsmasq.d/vmwgnat/10-vmwg0.conf
        mode: "0644"
      notify:
        - Restart dnsmasq

    - name: Create network interfaces.d directory
      ansible.builtin.file:
        path: /etc/network/interfaces.d
        state: directory
        mode: "0755"

    - name: Deploy vmwgnat network interface configuration
      ansible.builtin.template:
        src: templates/vmwgnat.j2
        dest: /etc/network/interfaces.d/vmwgnat
        mode: "0644"
      notify:
        - Restart networking

    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: Enable WireGuard service
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: true
        state: started

    - name: Start and enable dnsmasq
      ansible.builtin.systemd:
        name: dnsmasq
        enabled: true
        state: started

    - name: Check if vmwg0 interface is up
      ansible.builtin.command: ip link show vmwg0
      register: vmwg0_status
      failed_when: false
      changed_when: false

    - name: Bring up vmwg0 interface
      ansible.builtin.command: ifup vmwg0
      when: vmwg0_status.rc != 0 or 'state UP' not in vmwg0_status.stdout
      register: ifup_result
      changed_when: ifup_result.rc == 0

  handlers:
    - name: Restart wireguard
      ansible.builtin.systemd:
        name: wg-quick@wg0
        state: restarted

    - name: Restart dnsmasq
      ansible.builtin.systemd:
        name: dnsmasq
        state: restarted

    - name: Restart networking
      ansible.builtin.systemd:
        name: networking
        state: restarted
